### ISSUE TITLE
[FE] React qurey 및 axios 관련 토의

### ISSUE THREAD

**Issue by 2pandi** [codestates-seb/seb40_main_015#107]
의견을 자유롭게 남겨주십시오

**Comment by 2pandi** [comment]
axios 사용시 코드 컨벤션은 어떻게 할지
react query 보일러플레이트를 어떻게 가져갈지 결정해보면 좋을 것 같습니다.

**Comment by jooyong-boo** [comment]
<img width="757" alt="스크린샷 2022-11-18 오후 1 22 26" src="https://user-images.githubusercontent.com/93763666/202616228-ad38fa42-fcc2-497d-aec5-2b6e54f80361.png">

**Comment by Withlaw** [comment]
1. 우선 리액트 쿼리에 익숙해질때 동안 기존에 하던대로 진행하면서 쿼리는 리팩토링으로 작업하기.
-해당 컴포넌트에서 기존에 하던대로 useState, useEffect를 이용하여 AJAX call을 함
-api 통신이 원활하게 작동하면 리팩토링 진행

2. 쿼리로 리팩토링할 때 디렉토리 구조는 다음과 같이 함
예) 로그인 페이지에서 로그인 요청 api
src
ㄴapi
ㄴAuthAPI
-api.ts : postLogin 작성 (axios구문 사용)
-index.ts: useFetchLogin 작성 (react-query 구문 사용, 쿼리함수는 바로 위 api.ts/postLoginInfo를 임포트하여 사용)

**Comment by 2pandi** [comment]
<img width="283" alt="스크린샷 2022-11-18 17 22 05" src="https://user-images.githubusercontent.com/99231626/202655065-cecd58f3-83c1-4da2-b21d-6313f67b9ec6.png">

컨벤션 이건 어떠신지요 공식문서 뜯어왔습니다
